[workspace]
members = [
    "primitives",
    "runtime",
    "meta_contracts",
    "playgrounds",
]

[workspace.dependencies]
anyhow = "1"
borsh = { version = "1.0.0-alpha.6", features = ["derive"] }
